[package]
name = "jjs_kvm"
version = "0.1.0"
authors = ["Sergey Lisov <sleirsgoevy@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17.0"
anyhow = "1"
memmap = "0.7"
kvm-ioctls = "0.5"
kvm-bindings = "0.2"
