[package]
name = "jjs_kvm"
version = "0.1.0"
authors = ["Sergey Lisov <sleirsgoevy@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17.0"
anyhow = "*"
memmap = "*"
kvm-ioctls = "0.5.0"
kvm-bindings = "0.2.0"
